### PR TITLE
moved nested functions to top level for strict mode

### PR DESCRIPTION
**Pull request by slintes**
some browsers complained that functions may only be defined on top level in strict mode

### CODE REVIEW

**Comment by wulfsolter** [comment]
I've had a look and I can't replicate browsers complaining. Can you tell me a bit more?

**Comment by slintes** [comment]
See e.g. 2nd topic in this paragraph:  https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Strict_mode#Paving_the_way_for_future_ECMAScript_versions
I can try to create a simple test project tomorrow.

**Comment by slintes** [comment]
Here an example: http://plnkr.co/edit/OXJVbkL0BEAGNJKmxXgf?p=preview
Works in Chrome, but gives error in Firefox and Safari:
`SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function`

**Comment by wulfsolter** [comment]
Ah, nice! Thanks for the demo @slintes :)

**Comment by wulfsolter** [comment]
Updated on npm with 1.0.7

**Pull request merged**
